[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dumprx"
version = "2.0.0"
description = "Professional firmware extraction and analysis toolkit"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "DumprX Team", email = "dumprx@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Archiving",
    "Topic :: System :: Recovery Tools",
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.0.0",
    "rich>=13.0.0",
    "pyyaml>=6.0",
    "requests>=2.28.0",
    "gitpython>=3.1.0",
    "humanize>=4.0.0",
    "clint>=0.5.1",
    "tqdm>=4.64.0",
    "pathlib-mate>=1.0.0",
    "python-magic>=0.4.27",
    "py7zr>=0.20.0",
    "patool>=1.12",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "flake8>=5.0.0",
    "mypy>=1.0.0",
]

[project.scripts]
dumprx = "dumprx.cli:main"

[project.urls]
Homepage = "https://github.com/Eduardob3677/DumprX"
Repository = "https://github.com/Eduardob3677/DumprX"
Issues = "https://github.com/Eduardob3677/DumprX/issues"

[tool.setuptools.packages.find]
include = ["dumprx*"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true