name: Firmware Dump Workflow

on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: 'Firmware URL to dump'
        required: true
        type: string
      git_provider:
        description: 'Git provider to upload the dump'
        required: true
        type: choice
        options:
          - github
          - gitlab
        default: github
      github_token:
        description: 'GitHub Token (required if using GitHub provider)'
        required: false
        type: string
      github_orgname:
        description: 'GitHub Organization Name (optional, uses username if not provided)'
        required: false
        type: string
      gitlab_token:
        description: 'GitLab Token (required if using GitLab provider)'
        required: false
        type: string
      gitlab_group:
        description: 'GitLab Group Name (optional, uses username if not provided)'
        required: false
        type: string
      gitlab_instance:
        description: 'GitLab Instance URL (default: gitlab.com)'
        required: false
        type: string
        default: 'gitlab.com'
      telegram_token:
        description: 'Telegram Bot Token (optional, for notifications)'
        required: false
        type: string
      telegram_chat_id:
        description: 'Telegram Chat/Channel ID (optional, for notifications)'
        required: false
        type: string

env:
  PUSH_TO_GITLAB: ${{ inputs.git_provider == 'gitlab' }}

jobs:
  dump-firmware:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 8 hours timeout for large firmware files
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get remove -y '^aspnetcore-.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        
    - name: Set up Git LFS
      run: |
        git lfs install --global
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo chmod +x setup.sh
        ./setup.sh
        
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global http.postBuffer 524288000
        
    - name: Validate inputs
      run: |
        if [[ "${{ inputs.git_provider }}" == "github" ]]; then
          if [[ -z "${{ inputs.github_token }}" ]]; then
            echo "Error: GitHub token is required when using GitHub provider"
            exit 1
          fi
        elif [[ "${{ inputs.git_provider }}" == "gitlab" ]]; then
          if [[ -z "${{ inputs.gitlab_token }}" ]]; then
            echo "Error: GitLab token is required when using GitLab provider"
            exit 1
          fi
        fi
        
    - name: Setup authentication tokens
      run: |
        # Configure Python CLI with tokens
        if [[ "${{ inputs.git_provider }}" == "github" ]]; then
          python3 cli.py config set github_token "${{ inputs.github_token }}"
          if [[ -n "${{ inputs.github_orgname }}" ]]; then
            python3 cli.py config set git_org "${{ inputs.github_orgname }}"
          fi
        elif [[ "${{ inputs.git_provider }}" == "gitlab" ]]; then
          python3 cli.py config set gitlab_token "${{ inputs.gitlab_token }}"
          if [[ -n "${{ inputs.gitlab_group }}" ]]; then
            python3 cli.py config set git_org "${{ inputs.gitlab_group }}"
          fi
          if [[ -n "${{ inputs.gitlab_instance }}" ]]; then
            python3 cli.py config set gitlab_host "https://${{ inputs.gitlab_instance }}"
          fi
        fi
        
        # Setup Telegram tokens if provided
        if [[ -n "${{ inputs.telegram_token }}" ]]; then
          python3 cli.py config set telegram_token "${{ inputs.telegram_token }}"
        fi
        if [[ -n "${{ inputs.telegram_chat_id }}" ]]; then
          python3 cli.py config set telegram_chat "${{ inputs.telegram_chat_id }}"
        fi
        
    - name: Set PUSH_TO_GITLAB environment variable
      run: |
        if [[ "${{ inputs.git_provider }}" == "gitlab" ]]; then
          echo "PUSH_TO_GITLAB=true" >> $GITHUB_ENV
        else
          echo "PUSH_TO_GITLAB=false" >> $GITHUB_ENV
        fi
        
    - name: Run firmware dumper
      run: |
        echo "Using DumprX Python CLI v2.0"
        python3 cli.py extract '${{ inputs.firmware_url }}'
        
    - name: Cleanup sensitive files
      if: always()
      run: |
        # Cleanup config file with sensitive data
        rm -f ~/.dumprx/config.yml
        
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug-logs
        path: |
          out/tmp/
          *.log
        retention-days: 7